// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "table_name0", Type: field.TypeString},
		{Name: "table_name1", Type: field.TypeString},
		{Name: "table_name2", Type: field.TypeString},
		{Name: "table_name3", Type: field.TypeString},
		{Name: "table_name4", Type: field.TypeString},
		{Name: "table_name5", Type: field.TypeString},
		{Name: "table_name6", Type: field.TypeString},
		{Name: "table_name7", Type: field.TypeString},
		{Name: "table_name8", Type: field.TypeString},
		{Name: "table_name9", Type: field.TypeString},
		{Name: "table_name10", Type: field.TypeString},
		{Name: "table_name11", Type: field.TypeString},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "table_name0", Type: field.TypeString},
		{Name: "table_name1", Type: field.TypeString},
		{Name: "table_name2", Type: field.TypeInt},
		{Name: "table_name3", Type: field.TypeString},
		{Name: "table_name4", Type: field.TypeString},
		{Name: "table_name5", Type: field.TypeString},
		{Name: "table_name6", Type: field.TypeString},
		{Name: "table_name7", Type: field.TypeString},
		{Name: "table_name8", Type: field.TypeString},
		{Name: "table_name9", Type: field.TypeString},
		{Name: "table_name10", Type: field.TypeString},
		{Name: "table_name11", Type: field.TypeString},
		{Name: "table_name12", Type: field.TypeString},
		{Name: "table_name13", Type: field.TypeString},
		{Name: "table_name14", Type: field.TypeString},
		{Name: "table_name15", Type: field.TypeString},
		{Name: "table_name16", Type: field.TypeString},
		{Name: "table_name17", Type: field.TypeString},
		{Name: "table_name18", Type: field.TypeString},
		{Name: "table_name19", Type: field.TypeString},
		{Name: "table_name20", Type: field.TypeString},
		{Name: "table_name21", Type: field.TypeString},
		{Name: "table_name22", Type: field.TypeString},
		{Name: "table_name23", Type: field.TypeString},
		{Name: "table_name24", Type: field.TypeString},
		{Name: "table_name25", Type: field.TypeString},
		{Name: "table_name26", Type: field.TypeString},
		{Name: "table_name27", Type: field.TypeString},
		{Name: "table_name28", Type: field.TypeString},
		{Name: "table_name29", Type: field.TypeString},
		{Name: "table_name30", Type: field.TypeString},
		{Name: "table_name31", Type: field.TypeString},
		{Name: "table_name32", Type: field.TypeString},
		{Name: "table_name33", Type: field.TypeString},
		{Name: "table_name34", Type: field.TypeString},
		{Name: "table_name35", Type: field.TypeString},
		{Name: "table_name36", Type: field.TypeString},
		{Name: "table_name37", Type: field.TypeString},
		{Name: "table_name38", Type: field.TypeString},
		{Name: "table_name39", Type: field.TypeString},
		{Name: "table_name40", Type: field.TypeString},
		{Name: "table_name41", Type: field.TypeString},
		{Name: "table_name42", Type: field.TypeString},
		{Name: "altered_table_name43", Type: field.TypeString},
		{Name: "table_name44", Type: field.TypeString},
		{Name: "table_name45", Type: field.TypeString},
		{Name: "table_name46", Type: field.TypeString},
		{Name: "table_name47", Type: field.TypeString},
		{Name: "table_name48", Type: field.TypeString},
		{Name: "table_name49", Type: field.TypeString},
		{Name: "altered_table_name50", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductsTable,
		UsersTable,
	}
)

func init() {
}
