-- Modify "users" table
ALTER TABLE "users" ALTER COLUMN "table_name2" TYPE bigint;
-- Create "products" table
CREATE TABLE "products" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "table_name0" character varying NOT NULL, "table_name1" character varying NOT NULL, "table_name2" character varying NOT NULL, "table_name3" character varying NOT NULL, "table_name4" character varying NOT NULL, "table_name5" character varying NOT NULL, "table_name6" character varying NOT NULL, "table_name7" character varying NOT NULL, "table_name8" character varying NOT NULL, "table_name9" character varying NOT NULL, "table_name10" character varying NOT NULL, "table_name11" character varying NOT NULL, PRIMARY KEY ("id"));
